language: php
sudo: false
dist: trusty
php:
  - '5.6'
  - '7.1'

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"

before_install:
  # Disable xdebug.
  - composer self-update
  - composer validate --no-check-all --ansi

install:
  - travis_retry composer install --no-interaction --dev
  - composer info -i
  - wget https://github.com/clue/phar-composer/releases/download/v1.0.0/phar-composer.phar
  - chmod +x phar-composer.phar
  - php -d phar.readonly=off ./phar-composer.phar build

script:
  - ./vendor/bin/phpunit

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: 
  file: "audit.phar"
  skip_cleanup: true
  on:
    tags: true
    php: 5.6
